### ISSUE TITLE
ERR_INVALID_PACKAGE_TARGET

### ISSUE THREAD

**Issue by tayyab-gulzar** [PandaSekh/Url-Safety-Scanner#2]
Cannot start the application. Error [ERR_INVALID_PACKAGE_TARGET]: Invalid "exports" main target "dist/index.modern.js" defined in the package config E:\lb4\linksupercharger-loopback-server\node_modules\url-safety-scanner\package.json; targets must start with "./"

**Comment by PandaSekh** [comment]
Should be solved with version 1.0.4, please update
